main: com.github.mrmks.mc.efscraft.spigot.EffekseerCraft
name: EffekseerCraft
version: $version

commands:
  effek:
    usage: <command> <play|stop|clear|reload|reload> [sub...]
    permission: efscraft.command
permissions:
  efscraft.command:
    default: op
