modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
showAsResourcePack=false

[[mods]]
modId="efscraft"
version="$version"
displayName="EffeckseerCraft"
description="Play effekseer effects in minecraft."